### ISSUE TITLE
Not able to flash alternative firmware on light bulb

### ISSUE THREAD

**Issue by victormcezar** [SmartArduino/DoHome#10]
I'm trying to flash an alternative firmware on my light bulb using the java tool but I always get that my connection to lightbulb was refused

`java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.dohome.ota.Upgrade$1.run(Upgrade.java:140`

Is it possible to use this tool to flash an alternative firmware on light bulbs?
Or is there any other way to flash without having to soldering?

**Comment by HoGC** [comment]
You can try the latest version
https://github.com/SmartArduino/DoHome/tree/master/DoHome_HassAssistant_Component

**Comment by victormcezar** [comment]
I've tried this latest version of home assistant component, the auto discovery works fine but these are the problems I had:
 - wrong status of my lights: my lights were on and home assistant was showing that they were off
 - on/off not working: when I tried to turn off my lights, they changed to very low bright, wrong colors and still on
 
I'm using light bulbs with firmware 1.3.9 (DoHome app says it's updated)

**Comment by danieldabate** [comment]
> I've tried this latest version of home assistant component, the auto discovery works fine but these are the problems I had:
> 
> * wrong status of my lights: my lights were on and home assistant was showing that they were off
> * on/off not working: when I tried to turn off my lights, they changed to very low bright, wrong colors and still on
> 
> I'm using light bulbs with firmware 1.3.9 (DoHome app says it's updated)

Hey Victor! You might not be needing this info anymore, but I was having the same issue today when trying to flash a DoHome RGBWW light bulb.

I got it solved by either one of those 2 things that you might want to try:
1. Unbinding the light bulb from my account in the DoHome app. This is done by choosing the device inside the app -> ... -> Bind device -> Tap on your account and accept the unbind. This action gave me an error, but maybe it did something anyway.
2. Pressing the flash button while inside the DoHome app with the light bulb selected.

I'm not sure which of those two actions fixed the issue, but the upgrade went well after that. 

Then I flashed a Tasmota firmware to debug and get the right GPIO outputs and finally flashed an ESPHOME firmware with the right config.

Not sure if the config will be the same for your light bulb, for mine it's:
GPIO4 - White cold
GPIO5 - Blue
GPIO12 - Red
GPIO13 - White warm
GPIO14 - Green

Hope this helps.
